### ISSUE TITLE
Makefile install flags incompatible with macOs version of `install`

### ISSUE THREAD

**Issue by stracaganasse** [k-lar/dynomark#3]
## description

While trying to `sudo make install` under macOs the `-D` flag returns an error as it is not defined

While this is the linux behaviour ([docs](https://linux.die.net/man/1/install))
```
-D
    create all leading components of DEST except the last, then copy SOURCE to DEST 
```

Looks like there is no equivalent under macOs, closest is `-d`
From `man install`:
```
-d      Create directories.  Missing parent directories are created as required.
```
which still does not work with how the current Makefile is written

## working version

I ran a modified version with this and it worked:
```Makefile
PREFIX ?= /usr/local # just to mirror where Homebrew puts symlinks, not sure if the best option
BINARY_NAME=dynomark

all: build

build:
	go build -o ${BINARY_NAME} .

run:
	go build -o ${BINARY_NAME} .
	./${BINARY_NAME}

install:
	@install -m755 ${BINARY_NAME} $(DESTDIR)$(PREFIX)/bin/${BINARY_NAME} # removed -D flag

uninstall:
	@rm -f $(DESTDIR)$(PREFIX)/bin/${BINARY_NAME}

clean:
	go clean
	rm ${BINARY_NAME}
```

## conclusion

I'm not sure if my version makes sense from a _best-practices_ point of view as I could not find resources to confirm it.
I still think it could be useful to add a warning in the README for this mismatch between operating systems.

**Comment by k-lar** [comment]
Oh I wasn't aware of that, thanks for opening this issue!
I think the best way to deal with this is to get rid of install -D for all unix-y systems and just use a tiny bit of shellscript to do the same thing:
```make
PREFIX ?= /usr
BINARY_NAME=dynomark

all: build

build:
	go build -o ${BINARY_NAME} .

run:
	go build -o ${BINARY_NAME} .
	./${BINARY_NAME}

install:
	# Create the bin directory if it doesn't exist (Mac doesn't support install -D)
	@if [ ! -d $(DESTDIR)$(PREFIX)/bin ]; then \
		mkdir -p $(DESTDIR)$(PREFIX)/bin; \
	fi

	@install -m755 ${BINARY_NAME} $(DESTDIR)$(PREFIX)/bin/${BINARY_NAME}

uninstall:
	@rm -f $(DESTDIR)$(PREFIX)/bin/${BINARY_NAME}

clean:
	go clean
	rm ${BINARY_NAME}
```

The `PREFIX` var can stay as `/usr`, because I'm pretty sure it's made in a way that you can modify it when you run the command:
```bash
PREFIX=/usr/local sudo make install
```
Would this be okay enough to support MacOS?

**Comment by stracaganasse** [comment]
I ran a quick round of tests and can confirm that 
```sh
sudo make PREFIX=/usr/local install
```
works as intended in installing with your new Makefile

One must then remember to pass the same argument when uninstalling for it to work
```sh
sudo make PREFIX=/usr/local uninstall
```

A mention of this for macos users should be more than enough  :)
Nice work on the nvim plugin as well!
I will play around with it to see if there's a way to interpret existing dataview blocks, as converting all existing queries would not be the first road I'd pick if possible.

---
  
For future reference, using default `/usr/bin` will output this on my system (Sonoma 14.4.1) regardless of superuser privileges
```
install: /usr/bin/dynomark: Operation not permitted
make: *** [install] Error 71
```

Edit: Forgot to mention that i tested also the missing folder creation and it worked as intended.

**Comment by k-lar** [comment]
Thanks for testing it out! I added new instructions for both MacOS and Windows and added download links to the binary files in the releases section (on the dev branch for now).

As for trying to interpret existing dataview blocks, I don't think that's possible, maybe some really simple ones but not much else. The syntax differs too much I'm afraid. Would be cool if there was some way to automatically translate dataview to dynomark but that won't be in the scope of this project and time soon.
